package com.semicolon.dhaiban.designSystem

import androidx.compose.ui.graphics.Color

data class DhaibanColor(
    val primary: Color,
    val primaryLight: Color,
    val primary100: Color,
    val mediumBrown: Color,
    val mediumBrownTwo: Color,
    val primaryDark: Color,
    val primarySemiDark: Color,
    val silverGray: Color,
    val whisperingBlue: Color,
    val white: Color,
    val background: Color,
    val splashBackground: Color,
    val antiqueLace: Color,
    val optionWhite: Color,
    val dimGray: Color,
    val black: Color,
    val black87: Color,
    val black60: Color,
    val black70: Color,
    val black38: Color,
    val darkGray: Color,
    val error: Color,
    val container: Color,
    val description: Color,
    val categoryBack: Color,
    val transparent: Color,
    val buttonTextGray: Color,
    val rustyRed: Color,
    val rustyRedTwo: Color,
    val greyishBrown: Color,
    val silver: Color,
    val warmGray: Color,
    val toupe: Color,
    val toupeTwo: Color,
    val whiteTwo: Color,
    val darkBeige: Color,
    val beigeTwo: Color,
    val greyishTwo: Color,
    val veryLightBrown: Color,
    val lightGray: Color,
    val darkerGray: Color,
    val emeraldGreen: Color,
    val ratingBarcolor:Color,
    val greyOfTextField:Color


)

val LightColors = DhaibanColor(
    primary = Color(0xFF945915),
    primaryLight = Color(0x99924E00),
    primaryDark = Color(0xFF502D04),
    primarySemiDark = Color(0xFF673E0F),
    primary100 = Color(0x99945915),
    mediumBrown = Color(0xFF855013),
    mediumBrownTwo = Color(0x68855013),
    silverGray = Color(0xFFAEAEAE),
    whisperingBlue = Color(0xFFF2F2F3),
    white = Color(0xFFFFFFFF),
    background = Color(0xFFF9FAFB),
    splashBackground = Color(0xFFF4EEE7),
    antiqueLace = Color(0xFFF4EEE7),
    optionWhite = Color(0xFFF2EEEa),
    dimGray = Color(0xFF6E6E6E),
    black = Color(0xFF000000),
    black87 = Color(0xDE000000),
    black60 = Color(0x99000000),
    black70 = Color(0xB3000000),
    black38 = Color(0x61000000),
    darkGray = Color(0x57000000),
    error = Color(0xFFFF5656),
    container = Color(0xFFF4EEE7),
    description = Color(0xFF343434),
    categoryBack = Color(0xFFe0e9f0),
    transparent = Color(0x00000000),
    buttonTextGray = Color(0xFF3B3B3B),
    rustyRed = Color(0xFFB81919),
    rustyRedTwo = Color(0xFF7C1B1B),
    greyishBrown = Color(0xFF444444),
    silver = Color(0xFFC8C7D3),
    warmGray = Color(0xFF989696),
    toupe = Color(0xFFCEB495),
    toupeTwo = Color(0xFFC3A27B),
    whiteTwo = Color(0xFFEBEBEB),
    darkBeige = Color(0xFFB38C5F),
    beigeTwo = Color(0xFFDFCDB9),
    greyishTwo = Color(0xFFABABAB),
    veryLightBrown = Color(0xFFD4BCA1),
    lightGray = Color(0xFFF5F5F5),
    darkerGray = Color(0xFFE0E0E0),
    emeraldGreen = Color(0XFF009714),
    ratingBarcolor = Color(0XFFFFC107),
    greyOfTextField = Color(0XFFf1f1f1)
)
